---

- name: Create Fedora DB User (pgsql)
  postgresql_user:
    name: "{{ fcrepo_db_user }}"
    password: "{{ fcrepo_db_password }}"

- name: Create Fedora DB (pgsql)
  postgresql_db:
    name: "{{ fcrepo_db_name }}"
    state: present
    owner: "{{ fcrepo_db_user }}"
  register: fcrepo_db_exists
